baseURL: "http://localhost:1313/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Good With Data CIC"

summaryLength: 20

params:
  title: "Good With Data CIC"
  description: "Data science and analytics consultancy helping organizations unlock the power of their data"
  images: 
    - "images/gwd_logo.png"

  logo: "gwd_logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Brighton, London, Manchester"
    - "Remote consultancy available"

  contact:
    - "hello@goodwithdata.org"

  copyright: "© 2025 Good With Data CIC All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Services"
      url: "/services"
      weight: 2

    - name: "Portfolio"
      url: "/portfolio"
      weight: 3

    - name: "Blog"
      url: "/post"
      weight: 4

    - name: "About"
      url: "/about"
      weight: 5

  buttons:
    - name: "Get in touch"
      url: "/#contact"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Services"
      url: "/services"
      weight: 2

    - name: "Portfolio"
      url: "/portfolio"
      weight: 3

    - name: "Blog"
      url: "/post"
      weight: 4

    - name: "About"
      url: "/about"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true
