baseURL: "https://goodwithdata.org.uk"
theme: "up-business-theme"
languageCode: "en-gb"

title: "Good With Data CIC"

services: 
  googleAnalytics: 
    id: "G-FGK41S25ET"

summaryLength: 20

params:
  title: "Good With Data CIC"
  description: "We are a non-profit, community interest company, that provides data-focused consultancy services to NGOs and the charity sector."
  images: 
    - "images/hero-image.png"

  logo: "images/GWD_logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedin: "#"

  location:
    - "Brighton"

  contact:
    - "hello@goodwithdata.org.uk"

  copyright: "© 2023 Good With Data All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "What we do"
      url: "/#"
      weight: 2

  buttons:
    - name: "Get in touch"
      url: "mailto:hello@goodwithdata.org.uk"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "What we do"
      url: "/#"
      weight: 2

taxonomies:
  series: "series"
  tags: "datascience data oriented consultancy ngo charity"
