baseURL: "https://goodwithdata.org.uk"
theme: "up-business-theme"
languageCode: "en-gb"

title: "Good With Data CIC"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Good With Data CIC"
  description: "Data science and analytics consultancy helping organizations unlock the power of their data"
  images: 
    - "images/gwd_logo.png"

  logo: "gwd_logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    linkedin: "https://www.linkedin.com/company/good-with-data-cic/"
#    instagram: "#"
#    facebook: "#"
#    twitter: "#"

  location:
    - "Brighton, London, Manchester"
    - "Remote consultancy available"

  contact:
    - "hello@goodwithdata.org"

  copyright: "© 2025 Good With Data CIC All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1
    - name: "What we do"
      url: "/what_we_do"
      weight: 2

  buttons:
    - name: "Get in touch"
      url: "/#contact"
      weight: 5
      pre: "btn btn-primary text-light"


taxonomies:
  series: "series"
  tags: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true
